name: 'Deploy of the web-server'
on:
  workflow_dispatch:
jobs:
  build:

    name: Run on Ubuntu
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # Конфигурация Python
        uses: actions/setup-python@v5
        with:
          # Установка версии Python
          python-version: '3.7'
      
      
      # Показывать какая версия Python установлена    
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      

      #настройка AWS credentials с сервисами GitHub
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1


      #вход в Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      #сборка и пуш образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/web-server:latest